<?php echo $this->getContent(); ?>
<div align="right">
    <?php echo \Phalcon\Tag::linkTo(array("replies/new", "Create Replies")) ?>
</div>

<div align="center">
    <h1>Search replies</h1>
    <?php echo \Phalcon\Tag::form(array("replies/search")) ?>
    <table align="center">
        <tr>
            <td align="right">
                <label for="reply_id">Reply</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("reply_id", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="users_user_id">Users Of User</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("users_user_id", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="topics_topic_id">Topics Of Topic</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("topics_topic_id", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="topics_users_user_id">Topics Of Users Of User</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("topics_users_user_id", "type" => "numeric")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="reply_body">Reply Of Body</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("reply_body", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="reply_created_date">Reply Of Created Of Date</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("reply_created_date", "size" => 30)) ?>
            </td>
        </tr>

        <tr>
            <td></td><td><?php echo \Phalcon\Tag::submitButton(array("Search")) ?></td>
        </tr>
    </table>
</form>
</div>