<?php echo \Phalcon\Tag::form("users/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo \Phalcon\Tag::linkTo(array("users", "Go Back")) ?></td>
        <td align="right"><?php echo \Phalcon\Tag::submitButton("Save") ?></td>
    <tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create users</h1>
</div>

    <table align="center">
        <tr>
            <td align="right">
            </td>
            <td align="left">
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="full_name">Full Of Name</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("full_name", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="email">Email</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("email", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="password">Password</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("password", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="date_joined">Date Of Joined</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("date_joined", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="username">Username</label>
            </td>
            <td align="left">
            <?php echo \Phalcon\Tag::textField(array("username", "size" => 30)) ?>
            </td>
        </tr>
    </table>
<?php echo \Phalcon\Tag::endForm() ?>
