<?php $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo \Phalcon\Tag::linkTo(array("categories/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo \Phalcon\Tag::linkTo(array("categories/new", "Create categories")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Cat</th>
            <th>Cat Of Name</th>
            <th>Cat Of Created Of Date</th>
            <th>Users Of User</th>
            <th>Cat Of Decription</th>
        </tr>
    </thead>
    <tbody>
    <?php
        if(isset($page->items)){
            foreach($page->items as $categories){ ?>
        <tr>
            <td><?php echo $categories->cat_id ?></td>
            <td><?php echo $categories->cat_name ?></td>
            <td><?php echo $categories->cat_created_date ?></td>
            <td><?php echo $categories->users_user_id ?></td>
            <td><?php echo $categories->cat_decription ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("categories/edit/".$categories->cat_id/$categories->users_user_id, "Edit")); ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("categories/delete/".$categories->cat_id/$categories->users_user_id, "Delete")); ?></td>
        </tr>
    <?php }
        } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="5" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo \Phalcon\Tag::linkTo("categories/search", "First") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("categories/search?page=".$page->before, "Previous") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("categories/search?page=".$page->next, "Next") ?></td>
                        <td><?php echo \Phalcon\Tag::linkTo("categories/search?page=".$page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>